extensions:
  commerce/extensibility/1:
    $include: src/commerce-extensibility-1/ext.config.yaml
  commerce/backend-ui/2:
    operations:
      adminBlogGrid:
        - type: web
          path: /admin/blog-grid
    menu:
      label: Magazine Hub
      parent: Content
    acl:
      resource: magazine-editorial-hub/admin
